name: Create release

on: [ push,workflow_dispatch,workflow_call,pull_request ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Java 17
        run: |          
          mvn clean compile package -DskipTests
          cp target/test-ton-libs.jar test-ton-libs.jar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: test-ton-libs v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./test-ton-libs.jar
          tag: v${{ github.run_number }}
          overwrite: true
          file_glob: true
